### ISSUE TITLE
Rnghelper

### ISSUE THREAD

**Issue by hokeenthong** [Selindrile/GearSwap#10]
First of all. Thanks for sharing. 

After following your instructions on your gearswap, I am getting the following issue. 

...error in the user function get_sets:...... /addons/GearSwap/libs/snaps-rnghelper_config.lua45: attempt to index upvalue 'confdict_mt' (a nil value)

**Comment by Selindrile** [comment]
That's one I haven't seen before, and it's part of a extension I use from Snaps for auto shooting, after taking a look I'm not sure what would cause the issue, but happy to try to try and figure it out with you over discord.

**Comment by Selindrile** [comment]
Going to close this issue until further notice as I can't seem to replicate it, please contact me on discord or here with more information if it's still a problem.
