### ISSUE TITLE
COR gear correction

### ISSUE THREAD

**Issue by cantreadcode** [Selindrile/GearSwap#2]
You've probably been wondering why your snake eye never resets. :D

Selindrile_Cor_Gear.lua, Line 60

`sets.precast.JA['Snake Eye'] = {legs="Lanun Culottes +1"}`

Should be

`sets.precast.JA['Snake Eye'] = {legs="Lanun Trews +1"}`

**Comment by Selindrile** [comment]
Whoops, yeah I believe they changed that recently, thanks!

**Comment by Selindrile** [comment]
@cantreadcode FYI, I am indeed Selindrile ingame, you did message me the other day, but I don't respond to any talk about anything third party ingame, if you wanted to ask or talk about something, hit me up in discord. ^^
