### ISSUE TITLE
AutoWS

### ISSUE THREAD

**Issue by bjggi** [Selindrile/GearSwap#21]
Hi

Thanks for your Work!

I have a Problem using //gs c autows with King's Justice , it ends with Error: /ws "" <t>

I tried //gs c autows "King's Justice" or 'King's Jusitce' and King\'s Justice. How do i get this working?

Thank you!

**Comment by Selindrile** [comment]
//gs c autows King's Justice    should work fine, if not, I probably have an issue that I never noticed because shortcuts is fixing it, which is mentioned as a required addon for full functionality of my GS anyway.
