### ISSUE TITLE
Curing Waltz II

### ISSUE THREAD

**Issue by samibutera** [Selindrile/GearSwap#24]
Hey!  I play using your gearswap on a private server because I still play retail and wanted to stop using two different GearSwap files.  Everything was working great until the last update, except now I've got an issue where it says I can't cast Curing Waltz II because I'm level 75 and it thinks it's connecting to Curing Waltz IV somehow.  Do you have any ideas as to what could cause it or how I could fix it?  Would be appreciated!

**Comment by Selindrile** [comment]
You'd need to overwrite the refine_waltz function by copying it from Sel-Utility and putting it into User-Globals and edit as needed, my files aren't really designed to be used by jobs that aren't Lv99.
