### ISSUE TITLE
Question: Warp / Suggestion: AutoAssist

### ISSUE THREAD

**Issue by bjggi** [Selindrile/GearSwap#27]
Hi

First, thank you for your work!

I have a question about the /warp function "Sel-Include.lua:745". If i use /warp it equips "Warp Ring" and uses it. When the "Warp Ring" has cooldown and i enter /warp again (and i have a Warp Cudgel in my inv), should it then use the Warp Cudgel instead? Or does this not work like a downgrade, maybe i read this wrong? Atm it says: "Warp Ring not available or ready to use" and nothing happens. (time_offset has been adjusted to my timezone)

Another question or suggestion. Do you have a Auto Assist implantet for Multiboxer? So that other Mules like RDM or COR, could assist/engage the Target of my Main when he engages or changes target. Would be really helpful to have something like this.

Best Regards

**Comment by Selindrile** [comment]
I don't currently have it defaulting based on cooldown but I could, that was the original plan and I never got around to it after adding cooldown checking but I'll likely add that, thanks for the reminder.

I don't have anything for auto assist in GS, does seem like something that should exist, though probably not there, I may add that to Sendalltarget, thanks for the suggestions.

**Comment by Selindrile** [comment]
On starting to work on it, I now remember starting to work on this and why I didn't, I can't check time availability if the gear is in a place that you can't equip it from (satch/sack) etc, which makes it a bit of a pain because generally I'd rather pull my warp ring out of satchel rather than anything else...  not sure if I can think of a smooth workaround or way to handle it.

**Comment by Selindrile** [comment]
My account isn't active at the moment, I pushed an update that should use the other items if one is on cooldown in theory, if ya can test would be appreciated.

**Comment by bjggi** [comment]
Downloaded all files new and made a clean install. 

- Warp Ring and Cudgel in inventory. 
- Using /warp 
- "Msg cant cast warp using Warp Ring"
- Equips Ring and Warps
- Ring on CD, using /warp
- "Msg cant cast warp using Warp Ring"
- Nothing happens
- When i /heal it says "Cancelling using Warp Cudgel"

Feel free to msg when u want me to do more testing.

**Comment by bjggi** [comment]
I also tested /sneak with thf/nin and no Nin-Tools. (Think it should use Silent Oil then?) Doesn't work either.

**Comment by Selindrile** [comment]
Clean install shouldn't be necessary at all, just a github pull should be fine,  and no I haven't added anything to the Ninja part yet was testing the warp thing to make sure it worked before expanding, do you have Discord bychance? Would make communicating easier. And I'll see if I can figure out what I overlooked.
