### ISSUE TITLE
Driving me crazy

### ISSUE THREAD

**Issue by Mcdougall1** [Selindrile/GearSwap#28]
I have been using your stuff for a very long time and its amazing... I just have one issue.. Its the readme...

7.) If you don't have my style Character luas already, then Inside your Gearswap\Data
folder, first copy, then rename the "Selindrile" folder once for each of your characters' names, you can click Rename.bat and for the first sequence enter: Selindrile, then enter your character's name for new sequence. (If it doesn't work you will have to rename these files **namually,** then delete Rename.bat in all folders except the Selindrile folder.

Please exchange your letters N and M for the love of all that is good.

Thank you! 💃

**Comment by Selindrile** [comment]
Wish you would've mentioned the word the typo was in, but fixed ;p, glad you're liking the files.
