### ISSUE TITLE
Function Error in Sel Utility / Precast error

### ISSUE THREAD

**Issue by wjctampa** [Selindrile/GearSwap#29]
The recent update to Sel Utilty line 658, causing my GS to not change gear. can you please take a look.

**Comment by wjctampa** [comment]
This error is only affecting the BRD Gearswap files.  All others work as intended.

**Comment by Selindrile** [comment]
I've pushed some more fixes in the meantime, lemme know if this is still an issue.

**Comment by wjctampa** [comment]
Just finished testing on BRD and BLU seems to be fixed now.  Thank you for the quick response, very much appreciated.

**Comment by Selindrile** [comment]
Np!
