### ISSUE TITLE
sel-include.lua: 1386: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by deathfrombelow** [Selindrile/GearSwap#30]
Last update caused me several different runtime errors, so I reinstalled gearswap and recloned repository.  Now getting gearswap/sel-include error.  Full error is:
GearSwap: Lua runtime error: gearswap/flow.lua:350: 
GearSwap has detected an error in the self_command: 
...FilesWindower/addons/gearswap/libs/sel-include.lua; 1386: attempt to index field '?' (a nil value).

**Comment by deathfrombelow** [comment]
Just checked all of the jobs and it only occurs on THF and PLD.

**Comment by Selindrile** [comment]
Will check into this soon, just saw the issue, fastest way to contact me is Discord in the future, but I do check this semi regularly also.

**Comment by Selindrile** [comment]
I think this is an issue of Gearswap not properly tracking player.equipment in some circumstances, there's not a ton I can do about it, try swapping your weapons with a gearswap command. (Cycling them with F7 until a new weapon comes on) it should fix the issue.

**Comment by deathfrombelow** [comment]
Solved!  I deleted the state.weapons portion so long ago because I had crap weapons.  Quick copy/paste from your lua fixed it.  Thank you.

**Comment by Selindrile** [comment]
Ah, glad you figured it out, wasn't what I was thinking!
