### ISSUE TITLE
BRD Lua Error

### ISSUE THREAD

**Issue by wjctampa** [Selindrile/GearSwap#31]
Hello Selindre,

I've been getting the below error in my BRD Gearswap since the update pushed yesterday.  Any thoughts?

16:07:41 > GearSwap: Lua runtime error: GearSwap/flow.lua:346:
16:07:41 >   
16:07:41 > GearSwap has detected an error in the user function self_command:
16:07:41 > G:\Windower - Kaaria\/addons/GearSwap/data/BRD.lua:335: attempt to index field '?' (a nil value)
16:07:41 > GearSwap: Lua runtime error: GearSwap/flow.lua:346:
16:07:41 >   
16:07:41 > GearSwap has detected an error in the user function self_command:
16:07:41 > G:\Windower - Kaaria\/addons/GearSwap/data/BRD.lua:335: attempt to index field '?' (a nil value)

**Comment by wjctampa** [comment]
Did some more checking, error seems to only appear when low on MP.

**Comment by Selindrile** [comment]
Looking into this now.

**Comment by Selindrile** [comment]
It's under 50% MP triggering the check for idleSet.main and it's skill but I'm unsure how that would create this error, if you can, give me more information about the specifics of what is in your idleset, if you have the items defined in your itemset present, etc.

**Comment by wjctampa** [comment]
I did not have any reference of an Refresh Idleset.  I'm copying what you have in yours and modifying to my gear.  I'll let you know in a few if that' worked.

**Comment by wjctampa** [comment]
Still giving me same error.  My Idle Gearsets below.

	sets.idle = {
		main={ name="Kali", augments={'MP+60','Mag. Acc.+20','"Refresh"+1',}},
		sub="Ammurapi Shield",
		range="Marsyas",
		head="Inyanga Tiara +2",
		body="Inyanga Jubbah +2",
		hands="Inyan. Dastanas +2",
		legs="Brioso Cannions +2",
		feet="Fili Cothurnes +1",
		neck="Loricate Torque +1",
		waist="Carrier's Sash",
		left_ear="Genmei Earring",
		right_ear="Aoidos' Earring",
		left_ring="Fortified Ring",
		right_ring="Warden's Ring",
		back="Solemnity Cape"}
		
	sets.idle.NoRefresh = {
		main="Daybreak",
		sub="Genmei Shield",
		ammo="Staunch Tathlum",
		head="Aya. Zucchetto +2",
		neck="Loricate Torque +1",
		ear1="Etiolation Earring",
		ear2="Sanare Earring",
		body="Ayanmo Corazza +2",
		hands="Bihu Cuffs +3",
		left_ring="Fortified Ring",
		right_ring="Shadow Ring",
		back="Solemnity Cape",
		waist="Carrier's Sash",
		legs="Aya. Cosciales +2",
		feet="Fili Cothurnes +1"}

	sets.idle.PDT = {
		main="Mafic Cudgel",
		sub="Genmei Shield",
		range="Marsyas",
		head="Aya. Zucchetto +2",
		body="Ayanmo Corazza +2",
		hands="Aya. Manopolas +2",
		legs="Brioso Cannions +2",
		feet="Aya. Gambieras +2",
		neck="Loricate Torque +1",
		waist="Carrier's Sash",
		left_ear="Genmei Earring",
		right_ear="Aoidos' Earring",
		left_ring="Fortified Ring",
		right_ring="Warden's Ring",
		back="Solemnity Cape"}
		
	sets.idle.MDT = {
		main={ name="Kali", augments={'MP+60','Mag. Acc.+20','"Refresh"+1',}},
		sub="Genmei Shield",
		range="Marsyas",
		head="Inyanga Tiara +2",
		body="Inyanga Jubbah +2",
		hands="Inyan. Dastanas +2",
		legs="Inyanga Shalwar +2",
		feet="Inyan. Crackows +2",
		neck="Warder's Charm +1",
		waist="Carrier's Sash",
		left_ear="Sanare Earring",
		right_ear="Hearty Earring",
		left_ring="Fortified Ring",
		right_ring="Inyanga Ring",
		back="Solemnity Cape"}

**Comment by Selindrile** [comment]
yeah, have some issues figured out, figuring out best way to fix

**Comment by Selindrile** [comment]
Closing for now, hoping this fixes all the issues that arose from this, lemme know if it does not.

**Comment by wjctampa** [comment]
Thank you for taking the time to correct the issue.  Everything is back normal now.
