### ISSUE TITLE
Fencer things

### ISSUE THREAD

**Issue by lili-ffxi** [Selindrile/GearSwap#32]
https://github.com/Selindrile/GearSwap/blob/943e915a7feef668381cfa86ee296ecf07a5006e/libs/Sel-Utility.lua#L2476

Two things:
1) Agoge Mufflers +3 have Fencer +1 on them
2) Fencer gear caps at 8 tiers no matter what, and the last tier gives only 30 tp bonus
(JP gifts do not counts towards this cap)

**Comment by Selindrile** [comment]
Thanks for the info! I'm not much of a warrior!

**Comment by Selindrile** [comment]
Fixed hopefully.
