### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by sefalon** [Selindrile/GearSwap#34]
so I followed your guide step by step but nothing loads in game. The old gear swap just had the folder data and what Lua. Now it goes gearswap gearswap data and folder i put my name on it with the gear Lua for all jobs. I switched those from your name to mine like it said  but gearswap never loads

**Comment by Selindrile** [comment]
Sorry bit hard to tell what's up by your description, highly recommend you using the discord for such problems as realtime communication will be much easier:
https://discord.gg/ug6xtvQ
