### ISSUE TITLE
midcast swap for puppetmaster magic not working

### ISSUE THREAD

**Issue by EricBowman78** [Selindrile/GearSwap#35]
I reloaded the latest version and even renamed my gear lua and copied yours as mine just to see if i did something. idle sets work, engaged sets work but when they cast it is not swapping gear. 
tp ws gear works as well

**Comment by ERIC-BOWMAN** [comment]
Any idea's on how i would go about fixing this?

**Comment by Selindrile** [comment]
I do think this is an issue on my end I need to fix, leaving this issue open to remind me to do so, my account isn't active right now so that makes testing troublesome.

**Comment by cptkel** [comment]
Hey Sel - this is what I was telling you about, happens to me as well.

**Comment by Selindrile** [comment]
Yep, like I said, I do think it's on my end, just haven't looked into it yet.

**Comment by EricBowman78** [comment]
I would be happy to log in and get on discord and help out in this process so you would not need and account if you want to setup a date and time.

**Comment by Selindrile** [comment]
Hit me up on discord and at some point we can do so for sure.

**Comment by Selindrile** [comment]
Fixed, though using a JA in the middle of the action is still an issue.
