### ISSUE TITLE
lua wont load

### ISSUE THREAD

**Issue by larimon95** [Selindrile/GearSwap#4]
runtime error: GearSwap/flow.lua:346:
gearswap has deteected an error in the user function get sets:
...windower4/addons/gearswap/libs/snaps-rnghelper.lua:145: attempt to imdex field 'profiles'  (a nil Value)
gearswap: Loaded your BLU.lua file!
runtime error: GearSwap/flow.lua:346:
gearswap has deteected an error in the user function get sets:
...windower4/addons/gearswap/libs/snaps-rnghelper.lua:145: attempt to imdex field 'profiles'  (a nil Value)
gearswap: Loaded your BLU.lua file!
runtime error: GearSwap/flow.lua:346:
gearswap has deteected an error in the user function get sets:
...x86)...windower4/addons/gearswap/libs/sel-include.lua:241
Gearswap: Cannot find the include file (sel-globalitems.lua).

**Comment by Selindrile** [comment]
Well, seems like at the very least you don't have the library files, and you'll get a much faster answer if you hit me up on the discord I mentioned in the files.

**Comment by larimon95** [comment]
omg i missed your response so sorry, my files are a little old got them
from a friend back about a year ago. is there a recommendation how i can
update everything other than the gear files? not sure what discord is, is
there a link you can send?
