### ISSUE TITLE
Midcast sets blinking during casting

### ISSUE THREAD

**Issue by RudraXIV** [Selindrile/GearSwap#40]
Hello there,
Ive had a problem for a few month on all my mages lua . When i cast a spell its going precast > midcast then switching back to idle or engaged set before the spell go off, then i dont get any of my enhancing, duration, healing, conserve mp sets bonuses.
Any idea where this could come from  ?

**Comment by Kilgannon2113** [comment]
This is usually a sign off fastfollow

**Comment by RudraXIV** [comment]
That was it , its fixed now ty
