### ISSUE TITLE
Pup lua issue

### ISSUE THREAD

**Issue by RudraXIV** [Selindrile/GearSwap#41]
Automaneuvers doesnt work anymore on my lua. I dont get any error from gearswap, its just dont use it. Any idea of the problem ?

**Comment by cptkel** [comment]
Hey Rudra, I was just on PUP yesterday for ambu and automaneuver was working as intended - I toggle it with Win + Pause/Break

**Comment by maudit867** [comment]
Be sure you're files are updated. I believe Selindrile has made some changes. If all your files are up-to-date look in the gear folder for Selindrile and open the PUP file, compare that to your own PUP file and make sure the maneuver portions match.

**Comment by Selindrile** [comment]
Not much information here to work with, but as is said, others are not having issues.

**Comment by RudraXIV** [comment]
I totally forgot that it was under autobuffmode... ^^'
