### ISSUE TITLE
DRK file not using Hachirin-no-obi under weather conditions for Drain and Dark WS

### ISSUE THREAD

**Issue by sh7054** [Selindrile/GearSwap#42]
I saw the logic in the libs about hachirin but it doesn't seem to be applying as I'm using shadow of death, infernal scythe, and drain in dynamis and it's not swapping in the obi. I got around this by overloading the job_post_precast and job_post_midcast functions in my gear file and added the hachirin logic at the top of both from the default_post_precast and default_post_midcast functions respectively.

**Comment by Selindrile** [comment]
These are oversights that weren't taken into account, fixing them now, TBH the Scythe WS I'm not surprised were never noticed due to rarity of use, but Drain I am, pushing a fix now.
