### ISSUE TITLE
useitem case sensitivity

### ISSUE THREAD

**Issue by rpiwetz** [Selindrile/GearSwap#44]
Would it be possible to make useitem not be case sensitive, maybe by changing line 2313 of Sel-Utility.lua from:
if v == item then
to:
if v:lower() == item:lower() then

Obviously I can get around this by having macros for all my use items, or try and use the correct case, but when I get it wrong, the item equips but never gets used.

Thank you for the great gearswap files.

**Comment by rpiwetz** [comment]
Sorry, line 2312

**Comment by Selindrile** [comment]
Done.
