### ISSUE TITLE
Missing Optional File: user-globals.lua

### ISSUE THREAD

**Issue by Gojito** [Selindrile/GearSwap#46]
I just setup this gearswap and am getting that message when gearswap loads up. I ran the rename.bat and have a Hoshino-Globals.lua. Hoshino is the name of my character. Should that one be renamed to user-globals.lua or am I missing something?

**Comment by Selindrile** [comment]
You're missing the words "optional" and "only diagnostic information" when it comes to this message, if you're seeing this you most likely have everything set up correctly.

**Comment by Gojito** [comment]
Thanks. I realized it's optional, but am wondering if it can be found anywhere in the repo and whether there is a benefit to having it.

**Comment by Selindrile** [comment]
It can only be found in your brain, the benefit is whatever you write, User-Globals is a place for you to put custom code in without breaking github updates, as is described by the giant text in all the files you shouldn't edit because it would break github updating.

**Comment by Gojito** [comment]
Ah got it. I had not read further than Please Do Not Edit This File. Thanks for the clarification!
