### ISSUE TITLE
DRK file errors during Sheol: Gaol on line 263

### ISSUE THREAD

**Issue by sh7054** [Selindrile/GearSwap#47]
THis is the line it's erroring out on:
if state.Stance.value == 'Hasso' and abil_recasts[138] < latency then

Probably because subjob is locked

**Comment by Selindrile** [comment]
Yes that is why, my account isn't active so I can't test, I'd need more information about how the subjob locking works in Sheol: Gaol, is there a buff? What's it's name? Does the subjob locking trigger the register event for job change?

**Comment by sh7054** [comment]
I'll take a look the next time I enter. There is a buff icon that denotes the subjob lock but I can't remember what it's called

**Comment by sh7054** [comment]
So the SJ debuff gained in odyssey gaol is called "SJ Restriction", I don't know if it triggers the job change event

**Comment by Selindrile** [comment]
Thanks, this requires changes in a lot of places and I haven't felt like it but will leave this open and tackle it at some point, for now a GS reload after receiving the buff may fix as a workaround for now.

**Comment by Dyamalos** [comment]
Should be the same status as in dreamland Dynamis when restricting subjobs.

**Comment by Selindrile** [comment]
Finally got around to this.
