### ISSUE TITLE
WAR - Impulse Drive (polearm ws)

### ISSUE THREAD

**Issue by hokeenthong** [Selindrile/GearSwap#48]
Hi, I tried to use impulse drive using shining one on war but it did not equip the impulse drive ws set as set by me in the gs. When I try other polearm ws, it does not change to any ws set as well, it just use what I was equipping when engaging. 

Thanks in advance.

**Comment by Selindrile** [comment]
Without more information it's hard to tell why that might be unfortunately.

**Comment by hokeenthong** [comment]
How can I provide you with more information? I can attach my war gear file.

**Comment by Selindrile** [comment]
You could put it on pastebin.

**Comment by hokeenthong** [comment]
https://pastebin.com/ZqTM3tLw

Here you go. Thanks for your time.

**Comment by Selindrile** [comment]
I don't see anything that jumps out at me on the set specifically, other WS sets are working fine?

**Comment by hokeenthong** [comment]
The rest of the WS sets which are not polearm were working. I also only realised that polearm ws were not working when a friend told him this problem and he used my ws as a base to input his gear. After going through his gear file, I could not find any problem so I decided to try mine as well and the same problem arises.

**Comment by hokeenthong** [comment]
I think I solved it but do not know why. First, I use your war_gear lua and insert my impulse drive set and it works. Then, I compared what is different from the 2 war_gear lua and deleted 

"    -- Mighty Strikes WS Set --
    sets.MS_WS = {ammo="Yetshila +1", feet="Boii Calligae +1", 
    body={ name="Valorous Mail", augments={'Accuracy+30','Crit. hit damage +3%','STR+7',}},
	}	
"
and 

"function precast(spell,action)
	
	 if buffactive["Mighty Strikes"] then -- Equip MS_WS Set When You Have Mighty Strikes On --
                equipSet = set_combine(equipSet,sets.MS_WS)
            end
			end
"

After deleting these, it works.

**Comment by beerman212** [comment]
None of that looks like items that are in Selindrile's luas at all.  Are you sure you're using his luas?

For instance, this is his precast function

`
function precast(spell)
    handle_actions(spell, 'precast')
end
`

**Comment by beerman212** [comment]
The issue that you are experiencing is because you have defined the precast function (twice) in your lua and it has overridden all of the functionality in Sel's luas.

If you delete the 2 precast functions in your lua I would suspect that impulse drive will start working.  And any other WS that isn't Upheaval/King's Justice for that matter.

If you want to build custom WS set builds for different TP values on those two WS sets, I'd look at overriding a different function. Either override job_post_precast function that is in the WAR.lua, or create user_job_post_precast function.

**Comment by beerman212** [comment]
To elaborate,

You've made it so the precast function only does one thing.  It handle's Upheaval High/Low TP sets and King's Justice High/Low TP sets.

You've broken the functionality for literally everything else precast related.

You probably aren't equipping the right gear on JAs, You're not changing gear on any other WS's that aren't Upheaval/King's Justice.

overridding precast has probably broken everything for war, since there aren't any casting things unless you are /nin.

**Comment by Selindrile** [comment]
Yep these are definitely the issues, thanks Beerman, I completely skipped over those as I was focused on the sets themselves as he said other sets were working, you're overwriting the precast logic, twice, both times to "add" things that are already accounted for better in other files, and breaking everything else, there's no way your other WS sets should work, or JA, or precast on spells (which would only be Utsusemi generally for War but still)

**Comment by hokeenthong** [comment]
Yes, they are not inside the original file. I added them as I needed different sets at different TP for upheaval. Anyway I can add that in my file without breaking it?

**Comment by beerman212** [comment]
Probably the easiest way would be to do copy the job_post_precast function out of WAR.lua into your CharacterName_WAR_Gear.lua and then edit it.

`
function job_post_precast(spell, spellMap, eventArgs)
	if spell.type == 'WeaponSkill' then

		local WSset = standardize_set(get_precast_set(spell, spellMap))
		local wsacc = check_ws_acc()

        -- Next 5 lines are the only difference between the base function and yours
        local effective_tp = get_effective_player_tp(spell, WSset)

        if spell.name == "Upheaval" or spell.name == "King's Justice" and effective_tp < 2000 then
            WSset = standardize_set(set_combine(WSset, sets.precast.WS[spell.name].LowTP)) -- This would be the equivalent of your sets.UpheavalB or sets.KingsJusticeB sets
        end
        -- End changes
		
		if (WSset.ear1 == "Moonshade Earring" or WSset.ear2 == "Moonshade Earring") then
			-- Replace Moonshade Earring if we're at cap TP
			if get_effective_player_tp(spell, WSset) > 3200 then
				if wsacc:contains('Acc') and not buffactive['Sneak Attack'] and sets.AccMaxTP then
					local AccMaxTPset = standardize_set(sets.AccMaxTP)

					if (AccMaxTPset.ear1:startswith("Lugra Earring") or AccMaxTPset.ear2:startswith("Lugra Earring")) and not classes.DuskToDawn and sets.AccDayMaxTPWSEars then
						equip(sets.AccDayMaxTPWSEars[spell.english] or sets.AccDayMaxTPWSEars)
					else
						equip(sets.AccMaxTP[spell.english] or sets.AccMaxTP)
					end
				elseif sets.MaxTP then
					local MaxTPset = standardize_set(sets.MaxTP)
					if (MaxTPset.ear1:startswith("Lugra Earring") or MaxTPset.ear2:startswith("Lugra Earring")) and not classes.DuskToDawn and sets.DayMaxTPWSEars then
						equip(sets.DayMaxTPWSEars[spell.english] or sets.DayMaxTPWSEars)
					else
						equip(sets.MaxTP[spell.english] or sets.MaxTP)
					end
				else
				end
			else
				if wsacc:contains('Acc') and not buffactive['Sneak Attack'] and (WSset.ear1:startswith("Lugra Earring") or WSset.ear2:startswith("Lugra Earring")) and not classes.DuskToDawn and sets.AccDayWSEars then
					equip(sets.AccDayWSEars[spell.english] or sets.AccDayWSEars)
				elseif (WSset.ear1:startswith("Lugra Earring") or WSset.ear2:startswith("Lugra Earring")) and not classes.DuskToDawn and sets.DayWSEars then
					equip(sets.DayWSEars[spell.english] or sets.DayWSEars)
				end
			end
		elseif (WSset.ear1:startswith("Lugra Earring") or WSset.ear2:startswith("Lugra Earring")) and not classes.DuskToDawn then
			if wsacc:contains('Acc') and not buffactive['Sneak Attack'] and sets.AccDayWSEars then
				equip(sets.AccDayWSEars[spell.english] or sets.AccDayWSEars)
			elseif sets.DayWSEars then
				equip(sets.DayWSEars[spell.english] or sets.DayWSEars)
			end
		end
		
		if wsacc:contains('Acc') and not buffactive['Sneak Attack'] then
			if state.Buff.Charge and state.Buff['Mighty Strikes'] and sets.ACCWSMightyCharge then
				equip(sets.ACCWSMightyCharge)
			elseif state.Buff.Charge and sets.ACCWSCharge then
				equip(sets.ACCWSCharge)
			elseif state.Buff['Mighty Strikes'] and sets.ACCWSMighty then
				equip(sets.AccWSMighty)
			end
		else
			if state.Buff.Charge and state.Buff['Mighty Strikes'] and sets.WSMightyCharge then
				equip(sets.WSMightyCharge)
			elseif state.Buff.Charge and sets.WSCharge then
				equip(sets.WSCharge)
			elseif state.Buff['Mighty Strikes'] and sets.WSMighty then
				equip(sets.WSMighty)
			end
		end

	end

end
`

Change the name of your mighty strikes sets to:

sets.WSMighty
sets.AccWSMighty

**Comment by hokeenthong** [comment]
Thank you. Really appreciate your help on this. /bow
