### ISSUE TITLE
Having issue on BLU with idle sets not equipping despite toggle working

### ISSUE THREAD

**Issue by Flyingtaru** [Selindrile/GearSwap#49]
I have had this issue with another job (war or sam - can't recall), but now having the issue with BLU now (just started using the job). Used Windows-F12 and wanted a refresh idle and DT idle. I've repulled all Selindrile files via github desktop and and emptied gearswap addon to fresh as well. Then took base blu.gear.lua file and toggle works but doesn't equip gear (picking one piece of gear in DT so I know it was swapping). I turned on the gs debugmode and showswaps. Cast spell while in sets.idle.DT mode and would say equipping sets.idle only (not DT)... Have any guidance what may be the issue?

**Comment by Selindrile** [comment]
DT and Tank Idle sets default to normal idle when not in combat.

**Comment by Flyingtaru** [comment]
thank you!!
