### ISSUE TITLE
"Tick" stops working

### ISSUE THREAD

**Issue by bjggi** [Selindrile/GearSwap#54]
Hi 

I'm having a problem. I'm using your Gearswap for all my 6-Box Chars. Now alot of times, the Tick Function (Autobuff, AutoWs, UseItem etc.) just stops working from one moment to the other. Doesn't matter what i do or where i am (Ambu, Ody, Omen), somehow one or two chars stops using autows oder autobuff and i will have to reload Gearswap on that char to make it work again.

Any idear how this could be happing? Or is there a way for me to debug it? 

Im located in ECEST Timezone, using Windower 4 and Windows 10 (latest patch).

Best regards

**Comment by bjggi** [comment]
I did some testing doing Ambu. What i did was add a "add_to_chat" on the tick:

function pre_tick()
	add_to_chat(104, 'Tick')

So i can see the Ticks and when it stops. Now the Tick stopped sometimes on my Chars (Whm and then later RDM) when i zoned back to Mhaura from Ambu. Had to reload GS to make it tick again.

Now i tried to:

function default_zone_change(new_id,old_id)
	tickdelay = os.clock() + 18

I think this helped, the Tick didnt stop as much as before, or maybe this doesnt matter. I will try Ody on Tuesday and see how it works there, maybe it also occures while i zone up to the next floor.

**Comment by Selindrile** [comment]
I'm not sure what could possibly make it stop processing, and adding a higher delay shouldn't affect anything that could lead it to stopping, all it does is make it not process for a bit after zoning, delaying that for longer should only make it not process things before you might want it to start doing things automatically but shouldn't do anything that should derail tick, hrm

**Comment by bjggi** [comment]
Now i was able to do some further testing. 

Zoning doesn't seem to be the problem itself. When i zone between citys and my chars are doing nothing, the ticks are working fine. 

So how did the Tick sometimes stop when i zoned out from Ambu? Since Ambu forces you out even when u are casting, being stunned/slept or doing a JA, maybe the Problem lies when a Char gets interrupted.

I have to say, that i use CurePlease on Geo/Whm, Healbot on Rdm, and Roller on Cor and Uninterruptible (true) on all Chars. 

I was able to do one run of Sheol C today. My COR GEO and RDM stoped ticking. RDM stoped after it got hit by Sleepga, the COR stoped after roller did a Roll (not sure if he got hit by anything). And the GEO stoped after Cureplease got stuck in a "Current Action: Cure IV". It worked again after i casted a Cure IV.

So it could possible be a problem when a char is doing an action and he gets interuppted during a process. 

Should i maybe try to remove some of the Code for testing: delayed_cast or check_midaction, or silent_check_disable on the Tick? Or would that be a problem?

windower.raw_register_event('prerender', function()
if (player ~= nil) and (player.status == 'Idle' or player.status == 'Engaged') and not (delayed_cast ~= '' or check_midaction() or moving or buffactive['Sneak'] or buffactive['Invisible'] or silent_check_disable()) then

Best regards

**Comment by Selindrile** [comment]
I'm not sure, all of the actions that it's "waiting to finish" should have times where it eventually times out and stops waiting for them, so it shouldn't stop permanently, only for a few seconds, at worst.

**Comment by Noobcakes** [comment]
A few of my friends and I have been seeing the same behavior with autobuff/autows and occasionally the stance modes, etc (probably others, but those are the only ones I use regularly). 

Just eyeballing it, I'd say it's hanging when a JA/WS gets interrupted by another JA/WS or whatever (ie. it tries to ws and pop berzerk at the same time). 

I fiddled with it a little one day just popping off the abilities that are supposed to be automated manually using the menus. If I go through and use the abilities manually, usually it starts working again without having to reload gearswap.

**Comment by bjggi** [comment]
After some more testing, i was able to do 3 Ody runs and some Ambu runs without the Tick stopping! What i ended up with was removing the "delayed_cast" entirely and the "moving" from the tick.

So far that solved my problem, i hope :)

**Comment by Selindrile** [comment]
Actually, after what you said there and looking at it delayed cast makes a lot of sense to be the original culprit, considering I don't generally do a ton of automation in packet dropping zones it makes sense that I wouldn't have noticed it but this could've potentially been what's stopping people, moving also could be a culprit but I'm pretty sure that we've solved the "GS thinks you're moving but you're not" issue, going to push a small change and see if that fixes it for people at large.

**Comment by bjggi** [comment]
I was now able to test the new code, everything worked so far and I had no more interruptions with the Tick :)

Thank you!

**Comment by Selindrile** [comment]
Closing this as I haven't had anyone say this isn't working since the update.
