### ISSUE TITLE
Sel-Include Debug Line references incorrect variable

### ISSUE THREAD

**Issue by beerman212** [Selindrile/GearSwap#55]
`
-- Line 1451 Sel-Include.lua
function equip_gear_by_status(playerStatus, petStatus)
    if _global.debug_mode then add_to_chat(123,'Debug: Equip gear for status ['..tostring(status)..'], HP='..tostring(player.hp)) end
`
I believe this would generate an error if debug mode is turned on.  tostring(status) might need to be tostring(playerStatus) or tostring(player.status)

**Comment by Selindrile** [comment]
Fixed
