### ISSUE TITLE
Osash/Obi does not swap in for QuickDraw on COR

### ISSUE THREAD

**Issue by NickGL13** [Selindrile/GearSwap#56]
Looking at the code I don't think it is set up to do so, but would be great if it was added.

**Comment by beerman212** [comment]
It is definitely there.  You have to go to the default_post_precast function in the Sel-Include.lua to find it.

**Comment by NickGL13** [comment]
Okay so planning around again in game, it only comes on for sets.precast.CorsairShot and not in fodder mode when sets.precast.CorsairShot.Damage is used and when you would want extra damage from waist swapping. 
Thank you, I can swap the sets around or something

**Comment by beerman212** [comment]
You know what? I'm wrong, for some reason I was thinking weaponskills.  if you make this function

`
function user_job_post_precast(spell, spellMap, eventArgs)
  if spell.type == "CorsairShot" then

    if state.CastingMode.value ~= 'Proc' and spell.english ~= 'Light Shot' and spell.english ~= 'Dark Shot' then
      local orpheus_avail = item_available("Orpheus's Sash")
      local hachirin_avail = item_available('Hachirin-no-Obi')
				
      if hachirin_avail and spell.element and spell.element == world.weather_element and world.weather_intensity == 2 then
        equip({waist="Hachirin-no-Obi"})
      elseif orpheus_avail and spell.target.distance < 3 then
        equip({waist="Orpheus's Sash"})
      elseif hachirin_avail and spell.element and spell.element == world.weather_element and spell.element == world.day_element then
        equip({waist="Hachirin-no-Obi"})
      elseif orpheus_avail and spell.target.distance < 8 then
        equip({waist="Orpheus's Sash"})
      elseif hachirin_avail and spell.element and (spell.element == world.weather_element or spell.element == world.day_element) then
        equip({waist="Hachirin-no-Obi"})
      end
    end
  end
end
`

That should make it work.  I think

**Comment by NickGL13** [comment]
It works now just only with normal and not Fodder where damage set is normally. But I can add this and change code to if state.CastingMode.value == 'Fodder'
