### ISSUE TITLE
Obi Check - Orpheus's Sash

### ISSUE THREAD

**Issue by bjggi** [Selindrile/GearSwap#57]
Hey there

I was just pulling your Code for the new "Obi Check".

I testet it on my COR. When i WS "Leaden Salute" and i dont have Weather or Darks Day, it should swap in Orpheus's Sash right? If im between 1-15y. 

Unfortunately he doesn't swap that in for me. 

When i added your Test Code, my orpheus_intensity was 0.12442 when i was 5y away from the target. 0.034555 when im 14y away.

Maybe i misunderstand something.

PS. Hachirin works fine.

Best regards

**Comment by Selindrile** [comment]
fixed a few days ago
