### ISSUE TITLE
check_hasso()

### ISSUE THREAD

**Issue by bjggi** [Selindrile/GearSwap#58]
Something i noticed when i was switching my Weapons from 2h to 1h Sword (Warrior), the check_hasso was spamming the Hasso Ability.

Maybe something like this could be added to the check: main_weapon_is_one_handed() 

`if player.sub_job == 'SAM' and not state.Buff['SJ Restriction'] and not (state.Stance.value == 'None' or state.Buff.Hasso or state.Buff.Seigan or main_weapon_is_one_handed()) and player.in_combat and not silent_check_amnesia() then`

Best regards

**Comment by Selindrile** [comment]
added the main_weapon_is_one_handed() check and streamlined logic
