### ISSUE TITLE
Suggestion: AutoPositionMode

### ISSUE THREAD

**Issue by bjggi** [Selindrile/GearSwap#59]
Since i 6-Box i added a AutoPositionMode to your Gearswap. With this my Twinks, who also engage, turn to the target they attack. This is very helpful so that they turn permanently to the mob when you move around.

Now i know my LS likes this so i though other people would like this too, and maybe u want to add it or maybe even make it better :)

**Include:**
`state.AutoPositionMode 	  = M(false, 'Auto Position Mode')`

```
function pre_tick()
	if check_doomed() then return true end
        if check_trust() then return true end
        if check_rune() then return true end
	if check_shadows() then return true end
	if check_use_item() then return true end
	check_position()
	return false
end
```

**Utility**
```
function check_position()
	if state.AutoPositionMode.value and not moving then 
		if player.status == 'Engaged' and player.target.type == "MONSTER" then
			face_target()
		end
	end
end

```

Of course please feel free to discard this idea, if it's too much of a niche function.

**Comment by Selindrile** [comment]
Not too niche however, I personally handle this myself with another addon where it seems to fit better for me personally so don't plan on adding it to gearswap.
