### ISSUE TITLE
Auto ammo feature request

### ISSUE THREAD

**Issue by cantreadcode** [Selindrile/GearSwap#7]
Not really an issue... but a feature request. Would it be possible for the auto ammo to work on a per-weapon basis?
For example on corsair I have all 3 guns, but I don't need the same number of stacks of each bullet. I only ever need one stack of Living and Devastating at a time. I imagine it'd be even more-so a problem with all the ranger weapons out there. Thanks for reading and making awesome luas.

**Comment by Selindrile** [comment]
Would be possible, I'm intending to adjust the ammo feature, but it's not working at all right now due to a gearswap problem, I'll try to remember to add that when I also add belt support, but waiting for byrth to fix the issue first.

**Comment by Selindrile** [comment]
Update: Attempted to add belt support but the new ammo belt items aren't returning proper next_use_time due to their entry in extdata being off, so, that gets pushed back too till the windower people can get around to that.

**Comment by Selindrile** [comment]
Implemented but untested.
