### ISSUE TITLE
AutoDefenseMode

### ISSUE THREAD

**Issue by cantreadcode** [Selindrile/GearSwap#8]
Feel like I'm the only one out here lol...

So I've been messing around with your AutoDefenseMode. I like it a whole lot better than react because it doesn't require adding an entry for EACH monster. However, and you probably know this, it doesn't seem to know when the monster finished using an ability/spell. I ran into this problem when I tried making more specific sets for charm, stun, etc. resists.

I added this to the MonsterAbilities lua
```lua
CharmAbility = S{"Luminous Drape","Beautiful Death","Maiden's Virelai"}
```
Also added those abilities into AoEAbility and ResistAbility

and this set to my gear lua
```lua
sets.CharmResist = set_combine(sets.defense.MEVA, {
    neck="Unmoving Collar +1",ear1="Hearty Earring",ear2="Arete del Luna +1",
    ring1="Wuji Ring",
    back="Solemnity Cape"})
```

this in Stahp.lua where it handles the AutoDefenseMode

```lua
elseif ResistAbility:contains(act_info.name) and state.DefenseMode.value ~= 'Resist'  then
    if CharmAbility:contains(act_info.name) then
        do_equip('sets.CharmResist')
    else
        state.DefenseMode:set('Resist')
end
```

It detects the move and swaps gear, but problem is it will run the `send_command('gs c forceequip')` so fast that you're back in your engaged set before mob will fire off the move. Does it only work with `state.DefenseMode`'s? And if it does how can I go about making DefenseModes for specific status effects?

**Comment by Selindrile** [comment]
This would be easier to discuss on discord with a back and forth, if you wouldn't mind talking there, this is possible a number of ways.
