### ISSUE TITLE
Spell Recast function can be tuned

### ISSUE THREAD

**Issue by itomaldonado** [Selindrile/GearSwap#9]
The function `check_recast` in the `Sel-Utility.lua` file can be tuned a bit.

I noticed that if I spammed spells at the same speed I used to with the old GearSwap I get the error message: "Abort: <spell>  waiting on recast. ('00:00:00')". So if it is waiting on recast, why is the time 0?

Looking at how the `check_recast` function handles the timers, I saw that for ability recasts the timers provided by Windower are in seconds, but for spells it is a weird number that has to be divided by 60. So, sometimes when the ability is *actually* **off** cooldown this error still appears, I suggest changing the if statement on the line (see below) the following:

(Line in file: https://github.com/Selindrile/GearSwap/blob/master/libs/Sel-Utility.lua#L1106)
```
...
            if spell_recasts[spell.recast_id] > 0 then
				if stepdown(spell, eventArgs) then 
					return true
				else
...
```

to the following check (using floor and the division) so that it actually does the proper timer check and doesn't block when your spell is **actually** off cooldown:
```
...
            if math.floor(spell_recasts[spell.recast_id]/60) > 0 then
				if stepdown(spell, eventArgs) then 
					return true
				else
...
```

**Comment by Selindrile** [comment]
This is actually due to server latency, but point taken, I probably could take that into account, and I thought I remembered one of them being calculated in 60ths of a second, floor(recast/60) > 0 is just dividing the number by 60, and dropping the decimal. AKA If as far as your client knows the spell is within 1 second of cooldown, it treats it as already up for the purpose of blocking in gearswap, could do the same with <1 in abilities, no promises on when but I really should revisit this and do some latency testing and see where the number truly lies.

**Comment by Selindrile** [comment]
Implemented.

**Comment by larimon95** [comment]
had this working untill i had to reload lua not shure where to put it so when timers arent up it downgrades spells? please help
spell_stepdown = {
	['Aspir III'] = 'Aspir II',
	['Aspir II'] = 'Aspir',
	['Sleepga II'] = 'Sleepga',
	['Sleep II'] = 'Sleep',
	['Arise'] = 'Raise III',
	['Raise III'] = 'Raise II',
	['Raise II'] = 'Raise',
	['Reraise IV'] = 'Reraise III',
	['Reraise III'] = 'Reraise II',
	['Reraise II'] = 'Reraise',
	['Cure VI'] = 'Cure V',
    ['Cure V'] = 'Cure IV',
	['Cure IV'] = 'Cure III',
    ['Cure III'] = 'Cure II',
	['Cure II'] = 'Cure',
	['Curaga III'] = 'Curaga II',
	['Curaga II'] = 'Curaga',
	['Gravity II'] = 'Gravity',
	['Horde Lullaby II'] = 'Horde Lullaby',
	['Foe Lullaby II'] = 'Foe Lullaby',
	['Fire VI'] = 'Fire V',
    ['Fire V'] = 'Fire IV',
	['Fire IV'] = 'Fire III',
    ['Fire III'] = 'Fire II',
	['Fire II'] = 'Fire ',
    ['Firaja'] = 'Firaga III',
	['Firaga III'] = 'Firaga II',
	['Firaga II'] = 'Firaga',
	['Blizzard VI'] = 'Blizzard V',
    ['Blizzard V'] = 'Blizzard IV',
	['Blizzard IV'] = 'Blizzard III',
    ['Blizzard III'] = 'Blizzard II',
	['Blizzard II'] = 'Blizzard ',
    ['Blizzaja'] = 'Blizzaga III',
	['Blizzaga III'] = 'Blizzaga II',
	['Blizzaga II'] = 'Blizzaga',
	['Aero VI'] = 'Aero V',
    ['Aero V'] = 'Aero IV',
	['Aero IV'] = 'Aero III',
    ['Aero III'] = 'Aero II',
	['Aero II'] = 'Aero ',
    ['Aeroja'] = 'Aeroga III',
	['Aeroga III'] = 'Aeroga II',
	['Aeroga II'] = 'Aeroga',
	['Stone VI'] = 'Stone V',
    ['Stone V'] = 'Stone IV',
	['Stone IV'] = 'Stone III',
    ['Stone III'] = 'Stone II',
	['Stone II'] = 'Stone ',
    ['Stoneja'] = 'Stonega III',
	['Stonega III'] = 'Stonega II',
	['Stonega II'] = 'Stonega',
	['Thunder VI'] = 'Thunder V',
    ['Thunder V'] = 'Thunder IV',
	['Thunder IV'] = 'Thunder III',
    ['Thunder III'] = 'Thunder II',
	['Thunder II'] = 'Thunder ',
    ['Thundaja'] = 'Thundaga III',
	['Thundaga III'] = 'Thundaga II',
	['Thundaga II'] = 'Thundaga',
	['Water VI'] = 'Water V',
    ['Water V'] = 'Water IV',
	['Water IV'] = 'Water III',
    ['Water III'] = 'Water II',
	['Water II'] = 'Water',
    ['Waterja'] = 'Waterga III',
	['Waterga III'] = 'Waterga II',
	['Waterga II'] = 'Waterga',
	['Fira III'] = 'Fira II',
	['Fira II'] = 'Fira',  
	['Blizzara III'] = 'Blizzara II',
	['Blizzara II'] = 'Blizzara',
	['Aera III'] = 'Aera II',
	['Aera II'] = 'Aera',  
	['stonera III'] = 'stonera II',
	['stonera II'] = 'stonera',
	['Thundara III'] = 'Thundara II',
	['Thundara II'] = 'Thundara',  
	['Watera III'] = 'Watera II',
	['Watera II'] = 'Watera',	
	['Pyrohelix II']='Pyrohelix',
	['Cryohelix II']='Cryrohelix',
	['Anemohelix II']='Anemohelix',
	['Geohelix II']='Geohelix',
	['Ionohelix II']='Ionohelix',
	['Hydrohelix II']='Hydrohelix',
	['Luminohelix II']='Luminohelix',
	['Noctohelix II']='Noctohelix',

**Comment by Selindrile** [comment]
User-Globals.lua, which doesn't exist by default, create and add it there, if you only want it to be specific to a specific character, charactername. globals instead.

**Comment by larimon95** [comment]
Thank you!
